//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int id { get; set; }
        public int trip_id { get; set; }
        public decimal expense { get; set; }
        public string description { get; set; }
    
        public virtual Trip Trip { get; set; }
    }
}
