//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeSplitDBEntities : DbContext
    {
        public WeSplitDBEntities()
            : base("name=WeSplitDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<Joining> Joinings { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<PlaceImage> PlaceImages { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<RestStop> RestStops { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TripImage> TripImages { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
    }
}
