//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceImage
    {
        public int id { get; set; }
        public int place_id { get; set; }
        public string file_name { get; set; }
    
        public virtual Place Place { get; set; }
    }
}
